services:
  redis:
    image: redis:7-alpine
    container_name: rag_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
  # Using MongoDB Atlas via connection string; no local Mongo container required
  chroma:
    image: chromadb/chroma:0.5.23
    container_name: rag_chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    restart: unless-stopped
    command: "uvicorn chromadb.app:app --host 0.0.0.0 --port 8000 --proxy-headers"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: rag_api
    env_file:
      - .env
    # ADD THIS ENVIRONMENT BLOCK TO DISABLE TELEMETRY
    environment:
      - ANONYMIZED_TELEMETRY=False
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - chroma
    restart: unless-stopped
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: rag_worker
    env_file:
      - .env
    # This block is already here and is correct
    environment:
      - ANONYMIZED_TELEMETRY=False
    depends_on:
      - redis
      - chroma
    restart: unless-stopped
volumes:
  redis_data:
  chroma_data: